### ISSUE TITLE
Adding annoy to compute distance()

### ISSUE THREAD

**Issue by tmpfs** [danfinlay/fren-snap#1]
Hi @danfinlay,

Took a brief look at [RuAnnoy](https://github.com/hanabi1224/RuAnnoy) and compiles for `wasm32-unknown-unknown` and the `wasm-pack` tests pass so it looks like it's worth taking it for a spin.

The first issue I have encountered is that it seems like snaps doesn't yet support `wasm-pack` bundles which we will need to get the Javascript bindings.

This is the error I get trying to build the snap (when trying to compile with the `annoy-rs` webassembly bindings):

```
Build error: Unexpected token (413:46) while parsing /Users/muji/git/consensys/fren-snap/packages/snap/annoy/pkg/annoy_rs.js while parsing file: /Users/muji/git/consensys/fren-snap/packages/snap/annoy/pkg/annoy_rs.js
SyntaxError: Unexpected token (413:46) while parsing /Users/muji/git/consensys/fren-snap/packages/snap/annoy/pkg/annoy_rs.js while parsing file: /Users/muji/git/consensys/fren-snap/packages/snap/annoy/pkg/annoy_rs.js
    at DestroyableTransform.end [as _flush] (/Users/muji/git/consensys/fren-snap/node_modules/insert-module-globals/index.js:114:21)
    at DestroyableTransform.prefinish (/Users/muji/git/consensys/fren-snap/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:390:28)
    at prefinish (/Users/muji/git/consensys/fren-snap/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/Users/muji/git/consensys/fren-snap/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/Users/muji/git/consensys/fren-snap/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/Users/muji/git/consensys/fren-snap/node_modules/readable-stream/lib/_stream_writable.js:594:22)
    at Transform.onend (/Users/muji/git/consensys/fren-snap/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:596:10)
    at Object.onceWrapper (node:events:509:28)
    at Transform.emit (node:events:390:28)
    at endReadableNT (/Users/muji/git/consensys/fren-snap/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:1003:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'syntax',
  filename: '/Users/muji/git/consensys/fren-snap/packages/snap/annoy/pkg/annoy_rs.js',
  stream: Labeled {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { length: 0 },
      length: 0,
      pipes: [Labeled],
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Array],
      error: [Function (anonymous)],
      data: [Function: ondata],
      _mutate: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: false,
    allowHalfOpen: true,
    _options: { objectMode: true },
    _wrapOptions: { objectMode: true },
    _streams: [ [Deps] ],
    length: 1,
    label: 'deps',
    [Symbol(kCapture)]: false
  }
}
```

Which points to this code in the generated bindings:

```javascript
    imports.wbg.__wbg_new_898a68150f225f2e = function() {
        const ret = new Array();
        return addHeapObject(ret);
    };
```

And is caused by the `insert-module-globals` part of the build step:

```javascript
        try {
            var undeclared = opts.always
                ? { identifiers: varNames, properties: [] }
                : undeclaredIdentifiers(parse(source), { wildcard: true })
            ;
        }
        catch (err) {
            var e = new SyntaxError(
                (err.message || err) + ' while parsing ' + file
            );
            e.type = 'syntax';
            e.filename = file;
            return this.emit('error', e);
        }
```

I think it's probably better to get someone from the snap team to ensure that the snap compiler supports bundles generated by `wasm-pack` - what do you think?

**Comment by tmpfs** [comment]
If anyone wants to try this, I have added the code to this branch:

https://github.com/tmpfs/fren-snap/tree/annoy

And the annoy code is added as a submodule to the `packages/snap` directory so you will need to do the submodule dance.

Afterwards to compile the bindings:

```
cd packages/snap/annoy
wasm-pack build --target web
```

And then to generate the snap compiler error in the snap directory (after `yarn install` if necessary):

```
yarn build
```
